from django.db import models
import datetime

# Create your models here.
class User(models.Model):
    u_id = models.AutoField(primary_key=True)
    login_id = models.TextField(max_length=15, blank=True, unique=True)
    password = models.TextField(max_length=15, blank=True)
    name = models.TextField(max_length=15, blank=True)
    birth_date = models.TextField(max_length=15, blank=True)

    unknown_rate = models.FloatField(default=0, editable=True)
    action_rate = models.FloatField(default=0, editable=True)
    adventure_rate = models.FloatField(default=0, editable=True)
    animation_rate = models.FloatField(default=0, editable=True)
    children_rate = models.FloatField(default=0, editable=True)
    comedy_rate = models.FloatField(default=0, editable=True)
    crime_rate = models.FloatField(default=0, editable=True)
    documentary_rate = models.FloatField(default=0, editable=True)
    drama_rate = models.FloatField(default=0, editable=True)
    fantasy_rate = models.FloatField(default=0, editable=True)
    film_noir_rate = models.FloatField(default=0, editable=True)
    horror_rate = models.FloatField(default=0, editable=True)
    musical_rate = models.FloatField(default=0, editable=True)
    mystery_rate = models.FloatField(default=0, editable=True)
    romance_rate = models.FloatField(default=0, editable=True)
    sci_fi_rate = models.FloatField(default=0, editable=True)
    thriller_rate = models.FloatField(default=0, editable=True)
    war_rate = models.FloatField(default=0, editable=True)
    western_rate = models.FloatField(default=0, editable=True)

    unknown_num = models.IntegerField(default=0, editable=True)
    action_num = models.IntegerField(default=0, editable=True)
    adventure_num = models.IntegerField(default=0, editable=True)
    animation_num = models.IntegerField(default=0, editable=True)
    children_num = models.IntegerField(default=0, editable=True)
    comedy_num = models.IntegerField(default=0, editable=True)
    crime_num = models.IntegerField(default=0, editable=True)
    documentary_num = models.IntegerField(default=0, editable=True)
    drama_num = models.IntegerField(default=0, editable=True)
    fantasy_num = models.IntegerField(default=0, editable=True)
    film_noir_num = models.IntegerField(default=0, editable=True)
    horror_num = models.IntegerField(default=0, editable=True)
    musical_num = models.IntegerField(default=0, editable=True)
    mystery_num = models.IntegerField(default=0, editable=True)
    romance_num = models.IntegerField(default=0, editable=True)
    sci_fi_num = models.IntegerField(default=0, editable=True)
    thriller_num = models.IntegerField(default=0, editable=True)
    war_num = models.IntegerField(default=0, editable=True)
    western_num = models.IntegerField(default=0, editable=True)


class Movie(models.Model):
    m_id = models.AutoField(primary_key=True)
    title = models.TextField(max_length=30, blank=True)
    is_unknown = models.BooleanField(default=False)
    is_action = models.BooleanField(default=False)
    is_adventure = models.BooleanField(default=False)
    is_animation = models.BooleanField(default=False)
    is_children = models.BooleanField(default=False)
    is_comedy = models.BooleanField(default=False)
    is_crime = models.BooleanField(default=False)
    is_documentary = models.BooleanField(default=False)
    is_drama = models.BooleanField(default=False)
    is_fantasy = models.BooleanField(default=False)
    is_film_noir = models.BooleanField(default=False)
    is_horror = models.BooleanField(default=False)
    is_musical = models.BooleanField(default=False)
    is_mystery = models.BooleanField(default=False)
    is_romance = models.BooleanField(default=False)
    is_sci_fi = models.BooleanField(default=False)
    is_thriller = models.BooleanField(default=False)
    is_war = models.BooleanField(default=False)
    is_western = models.BooleanField(default=False)


class Rating(models.Model):
    r_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rate = models.IntegerField(editable=True)
    isUpdated = models.BooleanField(default=False, editable=True)

class Comment(models.Model):
    c_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    comment = models.TextField(blank=True)
    comment_date = models.DateTimeField(auto_now_add=True)

class WishList(models.Model):
    w_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)