# Generated by Django 2.1 on 2018-10-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=30)),
                ('is_unknown', models.BooleanField(default=False)),
                ('is_action', models.BooleanField(default=False)),
                ('is_adventure', models.BooleanField(default=False)),
                ('is_animation', models.BooleanField(default=False)),
                ('is_children', models.BooleanField(default=False)),
                ('is_comedy', models.BooleanField(default=False)),
                ('is_crime', models.BooleanField(default=False)),
                ('is_documentary', models.BooleanField(default=False)),
                ('is_drama', models.BooleanField(default=False)),
                ('is_fantasy', models.BooleanField(default=False)),
                ('is_film_noir', models.BooleanField(default=False)),
                ('is_horror', models.BooleanField(default=False)),
                ('is_musical', models.BooleanField(default=False)),
                ('is_mystery', models.BooleanField(default=False)),
                ('is_romance', models.BooleanField(default=False)),
                ('is_sci_fi', models.BooleanField(default=False)),
                ('is_thriller', models.BooleanField(default=False)),
                ('is_war', models.BooleanField(default=False)),
                ('is_western', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('isUpdated', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.TextField(blank=True, max_length=15, unique=True)),
                ('password', models.TextField(blank=True, max_length=15)),
                ('name', models.TextField(blank=True, max_length=15)),
                ('birth_date', models.TextField(blank=True, max_length=15)),
                ('unknown_rate', models.FloatField(default=0)),
                ('action_rate', models.FloatField(default=0)),
                ('adventure_rate', models.FloatField(default=0)),
                ('animation_rate', models.FloatField(default=0)),
                ('children_rate', models.FloatField(default=0)),
                ('comedy_rate', models.FloatField(default=0)),
                ('crime_rate', models.FloatField(default=0)),
                ('documentary_rate', models.FloatField(default=0)),
                ('drama_rate', models.FloatField(default=0)),
                ('fantasy_rate', models.FloatField(default=0)),
                ('film_noir_rate', models.FloatField(default=0)),
                ('horror_rate', models.FloatField(default=0)),
                ('musical_rate', models.FloatField(default=0)),
                ('mystery_rate', models.FloatField(default=0)),
                ('romance_rate', models.FloatField(default=0)),
                ('sci_fi_rate', models.FloatField(default=0)),
                ('thriller_rate', models.FloatField(default=0)),
                ('war_rate', models.FloatField(default=0)),
                ('western_rate', models.FloatField(default=0)),
                ('unknown_num', models.IntegerField(default=0)),
                ('action_num', models.IntegerField(default=0)),
                ('adventure_num', models.IntegerField(default=0)),
                ('animation_num', models.IntegerField(default=0)),
                ('children_num', models.IntegerField(default=0)),
                ('comedy_num', models.IntegerField(default=0)),
                ('crime_num', models.IntegerField(default=0)),
                ('documentary_num', models.IntegerField(default=0)),
                ('drama_num', models.IntegerField(default=0)),
                ('fantasy_num', models.IntegerField(default=0)),
                ('film_noir_num', models.IntegerField(default=0)),
                ('horror_num', models.IntegerField(default=0)),
                ('musical_num', models.IntegerField(default=0)),
                ('mystery_num', models.IntegerField(default=0)),
                ('romance_num', models.IntegerField(default=0)),
                ('sci_fi_num', models.IntegerField(default=0)),
                ('thriller_num', models.IntegerField(default=0)),
                ('war_num', models.IntegerField(default=0)),
                ('western_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.User')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.User'),
        ),
    ]
